#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=7-00:00:00
#SBATCH --mem=60G

# module loading
module purge
module load regenie/2.0.2

# current directory
pwd

# commands start
regenie \
    --step 1 \
    --bed /mnt/stsi/stsi1/ptseng/UKBB_Resources/filtered_noimpute_bed/ukb_cal_allChrs_prune \
    --phenoFile /gpfs/home/ptseng/Torkamani_Projects/20210830_PCa_UKBB/regenie_analysis/PCa_pheno.txt \
    --covarFile /gpfs/home/ptseng/Torkamani_Projects/20210830_PCa_UKBB/regenie_analysis/PCa_covar.txt \
    --remove /gpfs/home/ptseng/Torkamani_Projects/20210830_PCa_UKBB/regenie_analysis/excluded_individuals.remove \
    --exclude /mnt/stsi/stsi1/ptseng/UKBB_Resources/ID_list/ICLD_low-complexity.exclude \
    --bsize 1000 \
    --out /gpfs/home/ptseng/Torkamani_Projects/20210830_PCa_UKBB/regenie_analysis/PCa_ukb_step1_BT